### PR TITLE
Always submit environment data

### PR DESCRIPTION
**Pull request by AD7six**
If an exception is caught in a cli process - no environment information is submitted. 

This can make debugging cli problems difficult if there is more than one possible cli candidate-process. In my own situation, from sentry's info alone, I usually have to guess which process is throwing the exception based upon class names in a stack trace.

Annoyingly, whilst this does what I intended (add env data to the info submitted to sentry) it's considered invalid:

screenshot from 2015-12-02 12-18-32

What's the correct way to submit env data to sentry for cli processes? It should be automatic imo, and not "extra", I'm not sure which page in the spec-docs I should be referring to.

### CODE REVIEW

**Comment by AD7six** [comment]
no interest/comment?

**Comment by dcramer** [comment]
Sorry looks like we missed this ticket. 

You'd want to submit the cli info as part of extra as the HTTP interface is reserved for exactly what it sounds like. I do think it makes sense to capture more of this by default.

**Comment by AD7six** [comment]
> the HTTP interface is reserved for exactly what it sounds like

Can you clarify please what http interface you're referring to? The key under which `env` data is submitted for a cli request is `request`.

**Comment by dcramer** [comment]
@AD7six 'request' is an alias for the HTTP request. The reason env exists there is somewhat legacy, but because things like REMOTE_ADDR dont exist as HTTP headers and live in some kind of env.

**Comment by AD7six** [comment]
OK

Is it appropriate then to by default always submit env data via extra for cli processes?

**Comment by dcramer** [comment]
@AD7six yeah, it could simply be an "env" key on extra that contains the information

**Comment by dcramer** [comment]
I'm going to close this as we dont want environment data and its unclear if this is still valid.

**Pull request closed without merging**
