### PR TITLE
Prepare changelog for 1.8.1

### PR DESCRIPTION
**Pull request by stayallive**
Would like to release 1.8.1 (for #514).

Anything else that should go in / needs to be mentioned?

Or should this be 1.9?

### CODE REVIEW

**Comment by Jean85** [comment]
Also, you should include #515 too in the changelog!

**Comment by stayallive** [comment]
I added #515 :) You already had #514 in ;) (changelogs not working for you? 😉)

**Comment by Jean85** [comment]
Ops! Nope, I missed it, sorry!
So, only the constant needs to be fixed

**Comment by stayallive** [comment]
@Jean85 tagging guide wants readme up-to-date first, can merge to the release branch and change the version numbers there. Master should remain `1.9.x-dev`.

So when this is merged I will merge `master` to `release/1.8.x` and change the client version there, and tag that commit. I believe that is how the tagging guide want's it to go for patch versions.

**Comment by Jean85** [comment]
The `releases/1.8.x` branch doesn't exist yet, and I don't think it should be needed before 1.9.0 is released; to be fair, we don't even know yet if we will ever release it!

What do you mean with updating the Readme?

**Comment by stayallive** [comment]
Tagging a Release
-----------------

1. Make sure ``CHANGES`` is up to date (add the release date) and ``master`` is green.

> This is what this PR does.

2. Create a new branch for the minor version (if not present):

```
$ git checkout -b releases/1.9.x
```

> Branch exists (now). I apperently did not push that branch for the 1.8.0 release which should have been done.
> Instead of creating the branch, master will be merged into it to get the latest changes in

3. Update the hardcoded version tag in ``Client.php``:

```
class Raven_Client
{
    const VERSION = '1.9.0';
}
```

> This will be done in the `releases/1.8.x`

4. Commit the change:

```
$ git commit -a -m "1.9.0"
```

> This will be done in the `releases/1.8.x`

5. Tag the branch:

```
git tag 1.9.0
```

> This will be done in the `releases/1.8.x` on the commit that changes the client version

6. Push the tag:

```
git push --tags
```

> Speaks for itself

7. Switch back to ``master``:

```
git checkout master
```

> Check

8. Add the next minor release to the ``CHANGES`` file:

```
## 1.10.0 (unreleased)
```

> This is just the unreleased tag that is added in this commit

9. Update the version in ``Client.php``:

```
class Raven_Client
{
    const VERSION = '1.10.x-dev';
}
```

> Since it;s a patch this is not relevant, already on `1.9.x-dev` in master.

10. Lastly, update the composer version in ``composer.json``:

```
    "extra": {
        "branch-alias": {
            "dev-master": "1.10.x-dev"
        }
    }
```

> Since it;s a patch this is not relevant, already on `1.9.x-dev` in master.

---

I added comment on how I interpreted this. I will not assume 1.9 is not coming, no need to since it's little effort to follow the guide 😄  and if it's not coming and 2.0 is next, that fine also 👍

**Pull request merged**
