### PR TITLE
PHPDoc, properties of classes, warnings, code coverage, code style

### PR DESCRIPTION
**Pull request by nokitakaze**
Sorry guys. I just can not see that anymore. I open my Idea and then I want to pull my eyes out.
warnings_in_main_class
actual_expected_swap
equals_wrap_codestyle

I added and fixed many phpdoc-comments of class methods.
I added properties in classes.

And impove code coverage.
code_coverage_improve

### CODE REVIEW

**Comment by dcramer** [comment]
This patch is great though I am worried about our ability to maintain it without linters/automated tooling.

**Comment by stayallive** [comment]
Maybe it's time for StyleCI or some other tool to enforce a coding style :) Big :+1: from me for this.

**Comment by nokitakaze** [comment]
I just tested [PHP CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer), but it seems Raven's codebase is fundamentally broken.

[PSR-0](http://www.php-fig.org/psr/psr-0/)
> A fully-qualified namespace and class **must** have the following structure \\\<Vendor Name\>\\(\<Namespace\>\\)\*\<Class Name\>

default

**Comment by dcramer** [comment]
@nokitakaze its not broken, we just historically support a lot of PHP versions which is why we don't use namespaces

**Comment by nokitakaze** [comment]
Oh sorry. I just forgot about these versions of PHP what don't support normal OOP

**Comment by dcramer** [comment]
Thanks again!

**Pull request merged**
