### PR TITLE
[2.0] Improve Client and refactor Context

### PR DESCRIPTION
**Pull request by Jean85**
This PR aims at cleaning up the client in respect of code style and to extract the context functionality from it, moving all the logic inside the `Raven\Context` object, that was kinda empty.

This is still WIP since I need to update docs and changelog accordingly.

### CODE REVIEW

**Comment by ste93cry** [comment]
What about making the `Context` class generic so that there aren't methods like `setUserEmail`? I see the context as just a container, so I think it makes sense to let users populate it the way they want

**Comment by Jean85** [comment]
Looking and the [Sentry API](https://docs.sentry.io/clientdev/interfaces/user/), it seems that it recognize the following fields:

 * `id`
 * `email`
 * `ip_address`
 * `username`

So it does make sense to have a specific specialized method for those; still, no one is forcing you to use them, you can still populate the `Context` as you see fit for your application. I just refactored those methods away from the `Client` into the `Context.

**Comment by ste93cry** [comment]
Aren't those properties collected by and stored in the user interface?

**Comment by Jean85** [comment]
Yes they are, so that's why it's needed to specify them with the right name:

 * in the tags:

sentry-user2

 * in the right column, to show the share of users that got the event:
sentry-user

**Comment by Jean85** [comment]
I've noticed that the changelog and the docs are outdated anyway, they should be redone in a separate PR, at the end of the work on 2.0.

After rebasing, this is no longer WIP, please review!

**Comment by nokitakaze** [comment]
Could you check if `email` & `username` could be viewed with Sentry interface?

**Comment by Jean85** [comment]
The username is shown, as seen on the screenshot before. For other infos I cannot check now, but they are shown on the tag for sure.

**Comment by stayallive** [comment]
All user info fields are shown in the Sentry interface (tenant_id and uuid in non-standard but do show up in the user section).

screen shot 2017-09-11 at 16 13 46

**Comment by Jean85** [comment]
Great then! I'll merge now, thanks for the reviews!

**Pull request merged**
