### PR TITLE
Fixes #367 - array_walk_recursive being possibly called with a string in case http['data'] is a raw string.

### LINKED ISSUE #367: SanitizeDataProcessor crashes when POST data contains RAW data (for instance JSON DATA)
Introduced with rev ba7ebd9.

```
 public function sanitizeHttp(&$data)
 +    {
          $http = &$data['request'];		          $http = &$data['request'];
 -        if (empty($http['cookies'])) {		 +        if (!empty($http['cookies'])) {
 -            return;		 +            $cookies = &$http['cookies'];
 +            if (!empty($cookies[$this->session_cookie_name])) {
 +                $cookies[$this->session_cookie_name] = self::MASK;
 +            }
 +        }
 +        if (!empty($http['data'])) {
 +            array_walk_recursive($http['data'], array($this, 'sanitize'));
          }		          }
 +    }

```

$http['data'] could be a string, which will crash 'array_walk_recursive' because the first argument should be an array.

So in this case the check should be:

```
if (is_array($http['data']) && count($http['data'])) {
 ...
}
```

Encountered while updating from v0.22 to v1.5.0.

### PR DESCRIPTION
**Pull request by niborb**
fixes #367

### CODE REVIEW

**Comment by niborb** [comment]
Yes sure, I will change it.

**Comment by niborb** [comment]
updated.

**Comment by dcramer** [comment]
One last tidbit here, as I'm pretty sure this is going to throw errors based on the order of checks:

```
$ php -r '$arr = array(); echo is_array($arr["foo"]);'
PHP Notice:  Undefined index: foo in Command line code on line 1
```

AFAIK the empty check needs to come first, as calling is_array on a missing element will choke.

**Comment by niborb** [comment]
Yes you are right. Updated again ;-)

**Comment by dcramer** [comment]
Thanks!

**Comment by niborb** [comment]
thanks!

**Pull request merged**
