### PR TITLE
[2.0] Enforce PSR-4 (and more?) in codestyle

### PR DESCRIPTION
**Pull request by Jean85**
This PR add a new rule to the code style to enforce that PSR-4 is correctly used in every class.

I would like to use this PR to discuss about the usage of a more strict code style. Those are the rules that I would like to add:

```php
[
    'no_empty_comment' => true,
    'no_empty_phpdoc' => true,
    'native_function_casing' => true,
    'new_with_braces' => true,
    'no_empty_statement' => true,
    'no_short_bool_cast' => true,
    'no_unused_imports' => true,
    'no_whitespace_before_comma_in_array' => true,
    'no_whitespace_in_blank_line' => true,
    'not_operator_with_successor_space' => true,
    'object_operator_without_whitespace' => true,
    'ordered_imports' => true,
    'php_unit_construct' => true,
    'php_unit_dedicate_assert' => true,
    'phpdoc_single_line_var_spacing' => true,
    'phpdoc_trim' => true,
    'psr4' => true,
    'random_api_migration' => true,
    'single_blank_line_before_namespace' => true,
    'space_after_semicolon' => true,
    'trailing_comma_in_multiline_array' => true,
    'trim_array_spaces' => true,
    'whitespace_after_comma_in_array' => true,
]
```
What do you think about it? If we do agree, I'll add them to this PR.

### CODE REVIEW

**Comment by nokitakaze** [comment]
```
    'no_empty_comment' => true,
    'no_empty_phpdoc' => true,
```

You force potential contributors to write documentation and comments.

**Comment by ste93cry** [comment]
>You force potential contributors to write documentation and comments.

This is a good thing, not a bad one... By the way, those flags according to the documentation does not enforce the presence of any PHPDoc block or comment, they only enforce that if there is one it's not empty. I would like to suggest the following ruleset, which is the one being used by the `@Symfony` project with a few modifications.

```php
'binary_operator_spaces' => true,
'blank_line_after_namespace' => true,
'blank_line_after_opening_tag' => true,
'blank_line_before_statement' => true,
'braces' => true,
'cast_spaces' => true,
'class_definition' => true,
'concat_space' => true,
'declare_equal_normalize' => true,
'dir_constant' => true,
'elseif' => true,
'encoding' => true,
'ereg_to_preg' => true,
'full_opening_tag' => true,
'function_declaration' => true,
'function_to_constant' => true,
'function_typehint_space' => true,
'hash_to_slash_comment' => true,
'include' => true,
'indentation_type' => true,
'is_null' => true,
'line_ending' => true,
'lowercase_cast' => true,
'lowercase_constants' => true,
'lowercase_keywords' => true,
'magic_constant_casing' => true,
'method_argument_space' => true,
'method_separation' => true,
'modernize_types_casting' => true,
'native_function_casing' => true,
'new_with_braces' => true,
'no_alias_functions' => true,
'no_blank_lines_after_class_opening' => true,
'no_blank_lines_after_phpdoc' => true,
'no_break_comment' => true,
'no_closing_tag' => true,
'no_empty_comment' => true,
'no_empty_phpdoc' => true,
'no_empty_statement' => true,
'no_extra_consecutive_blank_lines' => true,
'no_leading_import_slash' => true,
'no_leading_namespace_whitespace' => true,
'no_mixed_echo_print' => true,
'no_multiline_whitespace_around_double_arrow' => true,
'no_short_bool_cast' => true,
'no_singleline_whitespace_before_semicolons' => true,
'no_spaces_after_function_name' => true,
'no_spaces_around_offset' => true,
'no_spaces_inside_parenthesis' => true,
'no_trailing_comma_in_list_call' => true,
'no_trailing_comma_in_singleline_array' => true,
'no_trailing_whitespace' => true,
'no_trailing_whitespace_in_comment' => true,
'no_unneeded_control_parentheses' => true,
'no_unused_imports' => true,
'no_whitespace_before_comma_in_array' => true,
'no_whitespace_in_blank_line' => true,
'non_printable_character' => true,
'normalize_index_brace' => true,
'object_operator_without_whitespace' => true,
'php_unit_construct' => true,
'php_unit_dedicate_assert' => true,
'php_unit_fqcn_annotation' => true,
'phpdoc_align' => true,
'phpdoc_annotation_without_dot' => false,
'phpdoc_indent' => true,
'phpdoc_inline_tag' => true,
'phpdoc_no_access' => true,
'phpdoc_no_alias_tag' => true,
'phpdoc_no_empty_return' => true,
'phpdoc_no_package' => true,
'phpdoc_no_useless_inheritdoc' => true,
'phpdoc_return_self_reference' => true,
'phpdoc_scalar' => true,
'phpdoc_separation' => true,
'phpdoc_single_line_var_spacing' => true,
'phpdoc_summary' => true,
'phpdoc_to_comment' => true,
'phpdoc_trim' => true,
'phpdoc_types' => true,
'phpdoc_var_without_name' => true,
'pre_increment' => true,
'protected_to_private' => true,
'psr4' => true,
'return_type_declaration' => true,
'self_accessor' => true,
'short_scalar_cast' => true,
'silenced_deprecation_error' => true,
'single_blank_line_at_eof' => true,
'single_blank_line_before_namespace' => true,
'single_class_element_per_statement' => true,
'single_import_per_statement' => true,
'single_line_after_imports' => true,
'single_quote' => true,
'space_after_semicolon' => true,
'standardize_not_equals' => true,
'switch_case_semicolon_to_colon' => true,
'switch_case_space' => true,
'ternary_operator_spaces' => true,
'trailing_comma_in_multiline_array' => true,
'trim_array_spaces' => true,
'unary_operator_spaces' => true,
'visibility_required' => true,
'whitespace_after_comma_in_array' => true,
```

Which can be reduced to:

```php
'@Symfony' => true,
'@Symfony:risky' => true,
```

**Comment by Jean85** [comment]
I do not agree with two rules from the Symfony codestyle, in particular:
 * `concat_space` to none, I prefer spaced string concatenation
 * `phpdoc_align`

But since it is a huge ruleset, if you agree it's not an issue, I prefer having a good and comprehensive CS ruleset than discuss those.

**Comment by ste93cry** [comment]
>concat_space to none, I prefer spaced string concatenation

I prefer that too, I think that we can just add it with a `false` value after `@Symfony` to override the setting

>`phpdoc_align`

I find this useful when there is more than e.g. one `@param` line so that everyline looks vertically aligned and it's easier to spot which is the type and the argument name

**Comment by stayallive** [comment]
I personally like spaces around the concat and like my docblocks aligned. I think the rest is fine.

**Comment by Jean85** [comment]
Ok, I think we have a majority then :smile: I'll update this PR ASAP, and I'll split in two commits: adding the rules and fixing them. I hope that it will not bring too much conflicts!

**Comment by Jean85** [comment]
Ok I've put in place the rules, and I've added the few from my original suggestions that I think are feasible:

        'concat_space' => ['spacing' => 'one'],
        'not_operator_with_successor_space' => true,
        'ordered_imports' => true,
        'random_api_migration' => true,

I thought that we would have a lot more violations! Good!

**Comment by ste93cry** [comment]
I would not use `not_operator_with_successor_space`. It's a preference of course, but I dislike seeing `if (! $variable)` vs `if (!$variable)`

**Comment by Jean85** [comment]
I prefer that to make it more visible, missing a not when reading a condition IMHO should be prevented.

Up to votes, do you prefer with or without space @stayallive @nokitakaze ?

**Comment by nokitakaze** [comment]
Contacatination strings? Without space of course

**Comment by stayallive** [comment]
My vote would be for `if (!$variable)` I find this readable enough.

**Comment by Jean85** [comment]
Ok I'll back down for spacing after negations.
@nokitakaze sorry but for the spacing around concat the consensus is using spaces (3 in favor).

**Comment by ste93cry** [comment]
>@nokitakaze sorry but for the spacing around concat the consensus is using spaces (3 in favor).

I'm not changing my opinion on the matter, I would just point out  that I see a lot of projects not using spacing around concat operator 😉

**Pull request merged**
