### PR TITLE
Ensure compatibility PHP 7.4 (cherry picked from #894)

### PR DESCRIPTION
**Pull request by Jean85**

### CODE REVIEW

**Comment by ste93cry** [comment]
This needs rebase on top of `master`

**Comment by Jean85** [comment]
@ste93cry it does not, it's already up to date. I don't know why the diff is messed up here, it shows differently locally, and I've re-pulled and asked for a rebase too.

**Comment by ste93cry** [comment]
Then I think that you are effectively reverthing the changes introduced with the previous commit and you just need to discard them manually

**Comment by Jean85** [comment]
I did:
```
git reset --soft master
# reviewed
git commit -am "..."
git push --force-with-lease
```

It should be fine, but the diff here on GitHub is still wrong, I don't know why!

**Comment by Jean85** [comment]
My mistake. The local diff had some stuff hidden. It's now ok.

**Pull request merged**
