### PR TITLE
Feat: Allow passing an eventId as context

### PR DESCRIPTION
**Pull request by jwissels**
Had to open a new PR because i couldn't change source branch in the original PR ( https://github.com/getsentry/sentry-php/pull/1388 ) 

We would like to pass an `eventId` as a parameter in the `$record` so that we can communicate the `eventId` to other handlers in the logger.

### CODE REVIEW

**Comment by jwissels** [comment]
@cleptric is there a way i could get this on the backlog again? Was away for the holidays and missed the bot. 
Would really appreciate this feature

**Comment by cleptric** [comment]
Could you extend the use case a bit? I'm a bit hesitant to allow creating Event IDs based on abatiary context data.

**Comment by jwissels** [comment]
We use https://github.com/Seldaek/monolog to log to multiple destinations, sentry and slack most notably. 
We'd like to provide the `id` so that in the message in slack we can link straight to the exception in sentry.

**Comment by cleptric** [comment]
Could you not use Sentry's Slack integration to do this?

**Comment by jwissels** [comment]
We use business logic on when we want to log to slack which is hard to replicate in sentry. We also enrich the exception differently. 

In previous versions ( with the `RavenHandler` ) it was possible to pass an `id` via context data. Is there maybe a more elegant way then context data to get the `id`? I'm happy to refactor.

**Pull request closed without merging**
