### PR TITLE
Run CI tests for PHP 8.3

### PR DESCRIPTION
**Pull request by jnoordsij**
With a few RC's released and the final release coming up in november, it might be a good thing to start running tests on the new PHP.

I did not encounter any issues or deprecations while testing, so everything seems to be all ready 😄

### CODE REVIEW

**Comment by jnoordsij** [comment]
Note: when checking the related workflow code and previous PR's (#1245 and #1339), I noticed that adding the new version to the `Restrict lowest Symfony version on PHP 8.1 & 8.2` matcher was not needed. I found out (`composer update "symfony/options-resolver:3.4.43" --dry-run`) this is due to the addition of `phpbench` as dev dependency (see #1274), which requires `symfony/options-resolver ^4.2 || ^5.0`, so that the v3 version is invalid anyways. 

While for recent PHP versions this is perfectly fine, this does mean the lowest versions dependency tests don't test this particular `symfony/options-resolver` version anymore at all (see e.g. https://github.com/getsentry/sentry-php/actions/runs/6198920906/job/16830371050#step:9:85). I'm not sure if this is a real issue, if so, a follow-up issue should be opened.

**Comment by Jean85** [comment]
IMHO we should drop support for Symfony 3.4: it's EOL for a long time, so long that next month 4.4 will be EOL too!

**Comment by ste93cry** [comment]
>we should drop support for Symfony 3.4

I agree, but as usual this is a decision that will require a discussion with the guys at Sentry. Also, with version `4.0` of this SDK in development, I find it unlikely that we will stop supporting Symfony `3.4` now, but I think it's feasible in the next major

> I noticed that adding the new version to the `Restrict lowest Symfony version on PHP 8.1 & 8.2` matcher was not needed. I found out (`composer update "symfony/options-resolver:3.4.43" --dry-run`) this is due to the addition of `phpbench` as dev dependency (see #1274), which requires `symfony/options-resolver ^4.2 || ^5.0`, so that the v3 version is invalid anyways. 

This was surely unwanted, but there is no version of `phpbench` that is compatible with Symfony `3.4` unless we go way back to its version `0.16`. The question is if we're fine with the missing test of this version of the framework or not. If the answer is the latter, we should relax the constraint in the `composer.json` accordingly

**Review by cleptric — APPROVED** [review]

**Comment by cleptric** [comment]
We can remove `"symfony/options-resolver": "^3.4.43"` in version 4.0 of the SDK.
I'm more concerned about PHP version support and `^4.4.30` supports PHP >= 7.1.

**Pull request merged**
