### PR TITLE
Fix code example

### PR DESCRIPTION
**Pull request by Horttcore**

### CODE REVIEW

**Comment by ste93cry** [comment]
Since I'm evaluating in #788 to stop register implicitly the error handler in the `ErrorHandler::add*Listener` methods (and so make them non-static) to be future-proof I would change the example to something similar to

```php
$errorHandler = ErrorHandler::registerOnce();
$errorHandler->addErrorListener(...);
$errorHandler->addFatalErrorListener(...);
$errorHandler->addExceptionListener(...);
```

**Comment by ste93cry** [comment]
The PR I was talking about has been merged, but the changes will be available only from version `2.1`. Since the `UPGRADE-2.0.md` is targeting of course the `2.0` version it seems to me that the changes here are fine as they are, so LGTM

**Comment by ste93cry** [comment]
The PR I was talking about has been merged, but the changes will be available only from version `2.1`. Since the `UPGRADE-2.0.md` is targeting of course the `2.0` version it seems to me that the changes here are fine as they are except for the fact that as said by @Jean85 we should document that at least a listener should be added to report the errors. @Horttcore are you willing to address the requested changes so that we can merge this PR?

**Comment by stayallive** [comment]
I am closing this PR because of inactivity, I even believe this problem was eventually addressed.

**Pull request closed without merging**
