### PR TITLE
fix: Merge hint extra's from captureMessage in event extra's when pre…

### PR DESCRIPTION
**Pull request by Celine68**
…paring event

### CODE REVIEW

**Review by cleptric — CHANGES_REQUESTED** [review]
This will need a test case.

Mind sharing why you're proposing this change as well? 
Is there something not working on the product (https://sentry.io)?

**Comment by Gwemox** [comment]
Yes, the captureMessage method does not process the data provided in EventHint->extra : 
https://forum.sentry.io/t/eventhint-extra-does-nothing-when-using-capturemessage/15836

**Comment by cleptric** [comment]
@Gwemox Looks like the link is not working.
From our develop docs, https://develop.sentry.dev/sdk/unified-api/#terminology

> extra: Truly arbitrary data attached by client users. This is a deprecated feature but will continue to be supported for the foreseeable future. Users are encouraged to use contexts instead.

**Comment by Celine68** [comment]
@cleptric  It's impossible to add event context through the captureMessage function. Is the captureMessage function deprectaed then ? Because it's not indicated.

**Comment by stayallive** [comment]
This data should not be in the `EventHint` but in the scope, and also it shouldn't be in the `extra` anymore: https://docs.sentry.io/platforms/php/enriching-events/context/#additional-data.

You can set "extra" structured context like this: https://docs.sentry.io/platforms/php/enriching-events/context/#structured-context

In your case the second example might be exactly what you are looking for:

```php
\Sentry\withScope(function (\Sentry\State\Scope $scope) use ($e): void {
    $scope->setContext('character', [
        'name' => 'Mighty Fighter',
        'age' => 19,
        'attack_type' => 'melee'
    ]);

    \Sentry\captureMessage('The fighter is out of energy!');
    // or: \Sentry\captureException($e);
});
```

`withScope` only applies to the callback so it doesn't modify the global scope.

**Comment by Celine68** [comment]
A huge thanks @stayallive  ! It does work this way !

**Pull request closed without merging**
