### PR TITLE
feat: set monolog.extra

### PR DESCRIPTION
**Pull request by simPod**
https://github.com/getsentry/sentry-php/issues/1318#issuecomment-1129865484

### CODE REVIEW

**Comment by Jean85** [comment]
Duplicate of #1244, already merged in develop.

**Comment by simPod** [comment]
Hello @Jean85 I checked the PR and does not seem to read `$record['extra']`. Can you review?

**Comment by ste93cry** [comment]
We are not reading `extra` purposefully, as it's meant to be used by processors and we absolutely want to avoid logging anything blindly as it may result in exceptionally big messages

>The main difference is that `context` can be supplied in user land (it is the 3rd parameter to `Psr\Log\LoggerInterface` methods) whereas `extra` is internal only and can be filled by processors. The reason processors write to `extra` and not to `context` is to prevent overriding any user-provided data in `context`.

**Comment by JanTvrdik** [comment]
The `extra` values are provided by processors, but they are provided with the intention of being logged. See

* [ProcessIdProcessor](https://github.com/Seldaek/monolog/blob/d381140ca134f7ece43cd2c139d2207bb26dc329/src/Monolog/Processor/ProcessIdProcessor.php) or
* [HostnameProcessor](https://github.com/Seldaek/monolog/blob/d381140ca134f7ece43cd2c139d2207bb26dc329/src/Monolog/Processor/HostnameProcessor.php) or
* [MemoryUsageProcessor](https://github.com/Seldaek/monolog/blob/d381140ca134f7ece43cd2c139d2207bb26dc329/src/Monolog/Processor/MemoryUsageProcessor.php) or 
* [MemoryPeakUsageProcessor](https://github.com/Seldaek/monolog/blob/d381140ca134f7ece43cd2c139d2207bb26dc329/src/Monolog/Processor/MemoryPeakUsageProcessor.php)

**Comment by ste93cry** [comment]
You are right. I have no opinion against implementing support at this point, as long as logging is dependent on the `fillExtraContext` flag, so that in the worst case the user can still turn it off. @ Jean85 WDYT?

**Comment by simPod** [comment]
@ste93cry in that case the PR should be good as is

@JanTvrdik thanks for input

**Comment by ste93cry** [comment]
Because the branch got deleted, I cannot reopen this PR. If you can't too, please open a new one

**Comment by simPod** [comment]
mb. https://github.com/getsentry/sentry-php/pull/1330

**Pull request closed without merging**
