### PR TITLE
Allow populating breadcrumb timestamp with custom value

### PR DESCRIPTION
**Pull request by romainneutron**

### CODE REVIEW

**Review by Jean85 — COMMENTED** [review]
Hello, and thank you for your contribution.

Can you tell us why you would need such a feature?

PS: CI failure seems unrelated.

**Comment by romainneutron** [comment]
Hello,

We use sentry PHP in a legacy app that has its own monitoring system. Once an error happens, we create sentry event and  we convert our internal breadcrumbs to sentry breadcrumbs.
At the moment, those breadcrumbs all have the same timestamp since they are created lately. Allowing setting the breadcrumb timestamp will allow us to properly set the time the breadcrumb happened

**Review by ste93cry — CHANGES_REQUESTED** [review]
Can you please add a CHANGELOG entry and also both the method `withTimestamp()` and the related test method?

**Comment by romainneutron** [comment]
PR updated, comments addressed

**Review by Jean85 — CHANGES_REQUESTED** [review]
Changelog entry still missing; code LGTM, but we're still getting that strange error on PHP 8 + Windows

**Comment by ste93cry** [comment]
Hopefully, you don't mind that I took the liberty to update some things to either improve them or align them to current coding standard of the project

**Review by ste93cry — APPROVED** [review]
Hopefully, you don't mind that I took the liberty to update some things to either improve them or align them to the coding standard of the project

**Review by Jean85 — APPROVED** [review]

**Pull request merged**
