### PR TITLE
Fix: Change SanitizeDataProcessorTest to mask nested arrays - fixes #145

### LINKED ISSUE #145: Sanitize arrays
When a credit card number is posted as an array, sanitizing would be nice. I'll post a failing test case shortly.

### PR DESCRIPTION
**Pull request by matthewgoslett**
This PR resolves Issue https://github.com/getsentry/raven-php/issues/145

If an array key matches the field regex, all child values are masked recursively.
eg:

```
  'card_number' =>
  array(4) {
    [0] =>
    string(8) "********"
    [1] =>
    string(8) "********"
    [2] =>
    string(8) "********"
    [3] =>
    string(8) "********"



'card_number_nested_further' =>
  array(4) {
    [0] =>
    array(2) {
      'part' =>
      string(8) "********"
      'number' =>
      string(8) "********"
    }
    [1] =>
    array(2) {
      'part' =>
      string(8) "********"
      'number' =>
      string(8) "********"
    }
    [2] =>
    array(2) {
      'part' =>
      string(8) "********"
      'number' =>
      string(8) "********"
    }
    [3] =>
    array(2) {
      'part' =>
      string(8) "********"
      'number' =>
      string(8) "********"
    }
  }
```

I've also added 2 unit tests to demonstrate the nested masking.

### CODE REVIEW

**Comment by dcramer** [comment]
Is your goal to keep the structure of the value in tact?

To be explicit, that is to show the entire mapping of values vs saying '***** => *****' as a single flat key/value.

**Comment by matthewgoslett** [comment]
My original coded turned the array into a flat masked '*****', but this failed tests.  The failing unit test added in https://github.com/getsentry/raven-php/pull/147 expects a mapped masked array.

**Comment by matthewgoslett** [comment]
Hey

We've been using this in production for a while now without any issues.
Can you look at this again?
Thanks

**Comment by ste93cry** [comment]
As this issue is quite old and should have been fixed in version 2.0 of this library I'm going to close the issue.

**Pull request closed without merging**
