### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by pgrimaud**
Hi,

This tiny PR will fix : 

- 1 typo in `src/Breadcrumb.php`
- 2 typos in `src/ErrorHandler.php`

Best! :robot:

### CODE REVIEW

**Comment by ste93cry** [comment]
Would you mind rebasing against the `develop` branch?

**Comment by pgrimaud** [comment]
@ste93cry Done :)

**Comment by ste93cry** [comment]
You just changed the target branch, but still missing the rebase. Also, while you're at it, can you please suppress the `InvalidReturnStatement` error of Psalm in the `RepresentationSerializer` class? It keeps popping up, but to me it looks like a false positive

**Comment by pgrimaud** [comment]
@ste93cry Really done this time, sooorry. 🍺
I also removed Psalm false positive and fixed coding style.

**Pull request merged**
