### PR TITLE
PHP 8 Support

### PR DESCRIPTION
**Pull request by Jean85**
This is temporarily blocked by https://github.com/Jean85/pretty-package-versions/pull/25 (which in turn is blocked by https://github.com/phpspec/prophecy/issues/491)

### CODE REVIEW

**Comment by Jean85** [comment]
Closing/reopening to trigger CI restart.

**Comment by ste93cry** [comment]
I think that `phpspec/prophecy` has been updated to support PHP 8, can you please rebase the PR and check if everything works?

**Comment by ste93cry** [comment]
Please don't merge the branch on the PR but rebase instead to keep the history cleaner 😉 Also build is failing due to PHPStan

**Comment by Jean85** [comment]
History is not an issue since we do squash+merge; I prefer merges since they create less issues with conflicts.

PHPStan issue fixed.

**Comment by Jean85** [comment]
Blocked by #4408 (which is already fixed but unreleased)

**Comment by Jean85** [comment]
Also, I can't reproduce current failures locally :cry:

**Comment by ste93cry** [comment]
You can merge your changes with the one from #1093 (I think that it didn't got merged in time before the release of version 3.0 and then I forgot about its existence) as I did the big of the work already

**Comment by Jean85** [comment]
Done, but I still get those failures :( I get those only with PHPUnit 9 and using `--coverage-clover`

**Comment by ste93cry** [comment]
May it be because of XDebug not being compatible with PHP 8 yet?

**Comment by pilif** [comment]
The failure look to me like it was caused by https://github.com/vimeo/psalm/issues/4459 which has now been fixed and is in psalm 4.1.1

**Comment by pilif** [comment]
the remaining failures are caused by XDebug emitting a backtrace when reporting errors while running the `.phpt` tests.

Probably, the way how PHPUnit deals with the phpt tests has changed and previously, the phpt tests were run by a php instance that didn't have XDebug.

However, even if I add

```
--INI--
xdebug.default_enable=0
```

to the phpt tests to leave the stack trace alone, this doesn't fix some tests which seem to fail to actually call the sentry handlers with debug present in the phpt tests

**Comment by pilif** [comment]
with the just released XDebug 3, we can use `xdebug.mode = coverage` to force xdebug into coverage only mode. This fixes the tests:

https://github.com/pilif/sentry-php/commit/a8ca0cfa928a36384128a59354ea2a73b59d98e4

however, I don't know how to update xdebug for travis - heck, their [latest php builder](https://github.com/travis-ci/php-src-builder) doesn't even mention xdebug at all, so I'm unclear as to how they get xdebug installed

**Comment by ste93cry** [comment]
>I'm unclear as to how they get xdebug installed

I don't know honestly, better wait a few days to see what happens, anyway some of our dependencies are still not compatible with PHP8 so we cannot release anyway the new version. In the meanwhile @Jean85, if you have time I think it would be worth checking if reverting all those changes to the PHPT tests are still needed with XDebug 3

**Comment by chris-doehring** [comment]
Hi @Jean85,
I was able to find the issue why `error_handler_respects_error_reporting.phpt` keeps failing. Don't know if you solved that one, yet. If not, I created a pull request: https://github.com/getsentry/sentry-php/pull/1141

**Comment by chris-doehring** [comment]
Thanks for accepting my PR @ste93cry!
I was able to find another two issues, this time related to dependencies which are also related to php 8 support: https://github.com/getsentry/sentry-php/pull/1144

**Comment by ste93cry** [comment]
>Probably, the way how PHPUnit deals with the phpt tests has changed and previously, the phpt tests were run by a php instance that didn't have XDebug.

This is being tracked in sebastianbergmann/phpunit#4529

>this doesn't fix some tests which seem to fail to actually call the sentry handlers with debug present in the phpt tests

I tracked the issue down to [`PhpParser\Parser\Tokens\startLexing()`](https://github.com/nikic/PHP-Parser/blob/1d1bc8a36459d67acef508b952dad097960b110e/lib/PhpParser/Lexer.php#L88) that is called during the collecting of the  code coverage at the script shutdown and that resets the fatal error. As a consequence of this our handler runs, there is no error and so it does nothing. I'm not sure what changed in the middle of the call stack and how it worked before, so any help is welcome

**Comment by ste93cry** [comment]
Once nikic/PHP-Parser#736 gets merged finally the tests should pass and the build should be green

**Comment by chris-doehring** [comment]
The PHP-Parser package released a new version [v4.10.3](https://github.com/nikic/PHP-Parser/releases/tag/v4.10.3) including https://github.com/nikic/PHP-Parser/pull/736, but unfortunately Travis CI still keeps failing. The main reason is the "Segmentation fault" error. At this point, I think this is a problem in the Travis environment. When running the same tests locally or via GitHub actions, this error does not occur. I don't know if you want to stick with Travis here, but if not, feel free to use the GitHub actions I created [in my fork](https://github.com/chris-doehring/sentry-php/tree/feature/github-actions/.github/workflows).

However, apart from the CI stuff, there is still [one issue pending](https://github.com/chris-doehring/sentry-php/runs/1495711181):
As soon as code coverage is activated, the test `tests/phpt/error_handler_captures_out_of_memory_fatal_error.phpt` does not call the shutdown function whenever it runs out of memory. This only happens for the highest dependencies, but so far I have no clue what the issue might cause.

**Comment by Jean85** [comment]
Travis got its PHP 8 images!

I'll try one more run...

**Comment by chris-doehring** [comment]
I'm a bit surprised that the memory test was so easy to fix, but it makes a lot of sense that newer phpunit versions just use more memory when running with code coverage. I didn't think of that 😄 Nice work @ste93cry! If you now change the php 8 Travis image to `8.0snapshot`, Travis should be completely green. 🥳 [They are still working on a php `8.0` tag.](https://travis-ci.community/t/php-8-0-missing/10132/18)

**Review by stayallive — APPROVED** [review]
Thank you for the work on this, excellent 💪

**Review by ste93cry — APPROVED** [review]
Thanks to everyone that contributed some changes to make this PR work and thank you all for the patience. LGTM

**Comment by Bilge** [comment]
Can we get a tag for this? There is still no stable tag for PHP 8.

**Pull request merged**
