### PR TITLE
Allow configure breadcrumb amount

### PR DESCRIPTION
**Pull request by christophlehmann**

### CODE REVIEW

**Comment by christophlehmann** [comment]
The current limit of 100 seems a little bit high to me and i bet no one checks the last 100 error possibilities so lets make it configurable

**Comment by Jean85** [comment]
If I'm not mistaken, that limit is related to the fact that it's a server-side limitation.

BTW, I wouldn't add this option due to the fact that it shouldn't be an issue, since breacrumbs are collapsed in Sentry's web interface. Also, we are currently nearing an alpha release of the 2.0 SDK, we should avoid adding new (undocumented) features to the old version.

**Comment by HazAT** [comment]
Heads up, I change the base to `1.x` since this is the old `master`.
Current `master` branch is the `2.0` version of the SDK.
Version `1.x` will receive minor and patch releases from this branch from now on.

**Comment by ste93cry** [comment]
Since `2.0` has the `max_breadcrumbs` option that does exactly this and given that it's still in development and this change is really simple, I would simply adjust this PR backporting what we do in the newer version of the SDK (validating the option value and calling it the same between the two versions) and merging it

**Comment by ste93cry** [comment]
@christophlehmann  are you still interested in finishing this PR or can we close it?

**Comment by christophlehmann** [comment]
Lets close it.

**Pull request closed without merging**
