### PR TITLE
[1.x] Fixed curl verify host for synchronous mode

### PR DESCRIPTION
**Pull request by WyskyNet**
There is a small bug in latest 1.x version that disallow to connect to sentry when self-signed certificate used.

### CODE REVIEW

**Comment by ste93cry** [comment]
Please do not add the AppVeyor config file to the `1.x` branch since we are not willing to test Windows for such an old version

**Comment by WyskyNet** [comment]
> Please do not add the AppVeyor config file to the `1.x` branch since we are not willing to test Windows for such an old version

AppVeyor tests removed.

**Comment by ste93cry** [comment]
Can you please force-push again this branch to see if the AppVeyor build succeeds?

**Comment by Jean85** [comment]
No need to force push, I'll close/reopen to force a rebuild

**Comment by ste93cry** [comment]
Damn AppVeyor is still running even though `1.x` branch should not have it :angry:

**Comment by Jean85** [comment]
I tried disabling it myself, I think we need help from @HazAT or someone else.

**Comment by WyskyNet** [comment]
Hi, and what about adding a "empty" appveyor configuration to pass a test?

I would like to use fixed version on our projects as soon as possible :)

**Comment by ste93cry** [comment]
Please try to force-push again, issue should be solved AFAIK

**Comment by WyskyNet** [comment]
force push done

**Comment by ste93cry** [comment]
@HazAT fix seems to not work, could you please check if there is something else that can be done? Otherwise since we don't support Windows builds anyway on `1.x` branches if you can review and merge this PR it's fine to me

**Comment by WyskyNet** [comment]
And please dont forget to create some version tag after merge :)

Thanks

**Comment by ste93cry** [comment]
Can you please force push once again? Also revert the change to the `.gitignore` file :+1:

**Comment by Jean85** [comment]
I pushed the config for AppVeyor as YAML, so this will be merged in the 1.x branch and stop builds from starting.

It seems to have worked! :tada:

**Pull request merged**
