### PR TITLE
Fixed undefined variable

### PR DESCRIPTION
**Pull request by Toflar**
Fixed PHP notice `Notice: Undefined variable: active in ... lib/Raven/CurlHandler.php on line 96`.

Depending on your setup, notices are converted to exceptions so you don't forget about them ;-) This notice currently causes my test environment to fail.

### CODE REVIEW

**Comment by Toflar** [comment]
Failing tests unrelated.

**Comment by Jean85** [comment]
Unfortunately the failure is somewhat related... You're consuming more memory, hence changing the result of the (flaky) PHPT regression test. Can you try to change the memory limit to `16M` here?https://github.com/getsentry/sentry-php/blob/61c862beca7ff8f44ab1636a15e54df5c44de51d/test/Raven/phpt/fatal_reported_with_async.phpt#L44

**Comment by Toflar** [comment]
No idea how that can use more memory but well, done :)

**Comment by stayallive** [comment]
It does seem wierd to consume more memory by just adding a variable (that will be defined by php anyway)... still failing with the memory change though...

**Comment by Jean85** [comment]
Damn, now an other regression test is failing, this time under 5.3... I have to investigate this further.

**Comment by Toflar** [comment]
Yeah, I actually just wanted to get rid of the notice and I think what I did is pretty straightforward, isn't it? 😄

**Comment by stayallive** [comment]
It should, but those tests are really flaky and testing some arcane edge cases so who knows... maybe this is even a cause somehow... 😜

**Comment by Jean85** [comment]
I'm currently unable to reproduce the failure locally :cry:

**Pull request merged**
