### PR TITLE
[2.0] Prevent segmentation fault in Reflection->getParameters()

### PR DESCRIPTION
**Pull request by Caffe1neAdd1ct**
https://github.com/getsentry/sentry-php/pull/504

When a native php function has been disabled via disabled_functions (php.ini) calling getParameters() on the reflection object of the disabled function causes a segmentation fault on PHP 5.6.31.

Reproducible on both Arch Linux and CentOS 6 with the following script:

php.ini
```
disable_functions = "passthru"
```

console.php
 ```php
<?php

require_once 'vendor/autoload.php';

use Raven_Client;

$connection = false;
$client = new Raven_Client($connection);
$client->environment = 'test';
$client->install();

passthru('clear');
```

Run straight through either php or php-cli `php56 console.php` gives a segmentation fault as follows:
```
[1]    22373 segmentation fault (core dumped)  php56 console.php
```

Testing through php 7 does not segfault and reflection seems to be able to cope with the disabled function:

```
PHP Warning:  passthru() has been disabled for security reasons in /home/kandrews/NetBeansProjects/compareandrecycle.co.uk/console.php on line 12
PHP Stack trace:
PHP   1. {main}() /home/kandrews/NetBeansProjects/compareandrecycle.co.uk/console.php:0
PHP   2. passthru() /home/kandrews/NetBeansProjects/compareandrecycle.co.uk/console.php:12
```

### CODE REVIEW

**Comment by Caffe1neAdd1ct** [comment]
Tests may need looking at, can't see any introduced failures from this change.

**Comment by Jean85** [comment]
It seems to be failing due to code style issues, not tests...

**Comment by nokitakaze** [comment]
@Caffe1neAdd1ct, You could merge current branch, it has new code style

**Comment by Caffe1neAdd1ct** [comment]
@nokitakaze great thanks for the update, i'll rebase current 2.0 into this and hope :+1:

**Comment by Caffe1neAdd1ct** [comment]
```
Package operations: 0 installs, 1 update, 0 removals
  - Updating php-http/mock-client (v1.0.1 => v1.0.1): Downloading (connecting...)
                                             
  [Composer\Downloader\TransportException]   
  Could not authenticate against github.com  
```

Rebased the changes from upstream (getsentry) 2.0 into (Caffe1neAdd1ct) downstream which look like they've come through

**Comment by Caffe1neAdd1ct** [comment]
How do we fix / re-trigger a scrutinizer build?

**Comment by nokitakaze** [comment]
I'm afraid only owner of the project on Scrutinizer could do it

**Comment by Jean85** [comment]
A new push would trigger a new build.

**Comment by Jean85** [comment]
Closing in favor of #523

**Pull request closed without merging**
