### PR TITLE
build(ci): Use GitHub Actions

### PR DESCRIPTION
**Pull request by billyvg**
`travis-ci.org` is shutting down at the end of the year. Here is a draft to use GitHub Actions instead. Another option is to migrate to `travis-ci.com`.

### CODE REVIEW

**Comment by billyvg** [comment]
@HazAT who can I tag to take a look at this o.o

**Comment by ste93cry** [comment]
Thank you for the heads up on this, honestly I knew that `travis-ci.org` was shutting down but not when. While I don't have anything in contrary in the switch, I'm not sure that doing it is worth the time as we already have a fully working config for two CIs and I cannot think of any advantage of GitHub actions over Travis CI for our use-case. However, since I believe that you may want to standardize the services used across all SDK projects, I will gladly accept any outcome of this discussion 👍

**Comment by Jean85** [comment]
IIRC Travis is also limiting the hours of execution for CI projects...
Also, Actions, due to the native integration, are pretty responsive compared to any other solution.

**Comment by ste93cry** [comment]
>IIRC Travis is also limiting the hours of execution for CI projects

I don't know, but we never had a problem with this

>are pretty responsive compared to any other solution

I have to admit that I don't see a difference between Travis and GitHub, and I feel that the UI of the GitHub Actions is more cucumbersome and slow because each step is collapsed and opening them take time to load the data. Anyway, if we decide to switch we should also switch the Windows builds over here as I don't see a benefit of keeping AppVeyor at that point

**Comment by Jean85** [comment]
Having a single CI with both Linux & Windows builds would be a nice perk, indeed!

**Comment by ste93cry** [comment]
I just saw in a recent PR that the project already got migrated to `travis-ci.com` by the way 😉

**Comment by billyvg** [comment]
@ste93cry yeah we mass migrated all of the repos over to `.com`, it doesn't look like there's too much interest in moving though, so we can close this. Feel free to ping me if this isn't the case and I can help finish this up.

**Comment by billyvg** [comment]
@ste93cry I'm re-opening this because of billing issues with Travis, we now definitely need to move off of Travis. They pulled some pretty shady stuff with billing and we're now being charged for all of our open source repos (with no warning afaik).

**Comment by ste93cry** [comment]
We switched to GitHub Actions already some time ago. Closing this again 😃

**Comment by billyvg** [comment]
🙈 Thanks!

**Pull request closed without merging**
