### PR TITLE
Add setters for Raven Serializes

### PR DESCRIPTION
**Pull request by atuzlukov**
Why? 
Add the ability to install a custom serializer. For example, instead of the phrase "Array of length 3" put a serialized array, so as not to lose valuable data during the logging

### CODE REVIEW

**Comment by stayallive** [comment]
I would be fine with this I think. @Jean85 what are your thoughts?

Assuming this is already implemented in 2.0, but still be usefull in 1.x.

**Comment by Jean85** [comment]
Nope, this is not implemented in 2.0, so it could be ported there to.

Can we add some tests?

**Comment by stayallive** [comment]
@atuzlukov would you be able to add some tests for this functionality?

**Comment by atuzlukov** [comment]
@stayallive @Jean85 Added tests for serialize setters

**Pull request merged**
