### PR TITLE
Remove link to unmaintained Nette community integration

### PR DESCRIPTION
**Pull request by WyskyNet**
Salamek/raven-nette is abandoned package and can be replaced by kdyby/monolog

### CODE REVIEW

**Comment by ste93cry** [comment]
I agree, please just remove the entry from the list

**Comment by Jean85** [comment]
It's still a community-supported integration, maybe we can just rename the link?

**Comment by ste93cry** [comment]
The original package is not supported anymore, and the suggested one is not sentry-specific as said by @stayallive. If there is not a replacement for the package we should just remove it instead of linking a deprecated package

**Comment by stayallive** [comment]
@Jean85 the replacement only adds monolog not even a note on how to add Sentry to that in the documentation (which is not wrong or a bad thing), so we should not link from Sentry that that is the way to go for Nette without it being either Sentry specific or have a note about how to integrate Sentry, no point in it.

Nothing wrong with the Nette Monolog package! And I don't expect them to add a piece of Sentry documentation or for that matter any of the other thousands of Monolog plugins.

@WyskyNet thanks for bringing to our attention the Nette package is no longer supported. Much appreciated!

**Pull request merged**
