### PR TITLE
feat(profiling): Made OsContext and RuntimeContext optional

### PR DESCRIPTION
**Pull request by idsulik**
Hi! Within the PR I made `OsContext` and `RuntimeContext` optional because it was a surprise for me when I tried to profile my application and I didn't receive profiling events so after debugging it turned out that I needed to enable EnvironmentIntegration to make it work.

p.s. I'll add test if it's ok to make them optional(who knows maybe the server requires these fields)

### CODE REVIEW

**Comment by stayallive** [comment]
This actually has a reason, it is required by the Sentry server so we cannot make them optional at this moment. The documentation for the profiles payload lives here: https://develop.sentry.dev/sdk/profiles/ in case you are interested.

**Comment by idsulik** [comment]
@stayallive thank you, could you please add information about EnvironmentIntegration to the doc? Because I've spent a lot of time to find the reason why I don't see the profiling event

**Comment by cleptric** [comment]
It's already there https://docs.sentry.io/platforms/php/profiling/troubleshooting/.

**Comment by idsulik** [comment]
oh, I've missed it, I think it should be on this page https://docs.sentry.io/platforms/php/profiling/ because without it you won't see profiling data.

**Comment by stayallive** [comment]
The `EnvironmentIntegration` is a default integration, so it makes sense it is in the troubleshooting section right since "normally" the integration would be enabled?

**Comment by idsulik** [comment]
okay, thank you!

**Pull request closed without merging**
