### PR TITLE
Symfony 5 compatibility

### PR DESCRIPTION
**Pull request by rvanlaak**
fixes https://github.com/getsentry/sentry-php/issues/922

related to https://github.com/getsentry/sentry-symfony/pull/266

tested by running phpunit locally

### CODE REVIEW

**Comment by ste93cry** [comment]
This should close #922 and I don't expect any issue with Symfony 5 anyway, but let's wait until we can really test it in the CI because right now the `highest` jobs are using the components at version `4.4`

**Comment by Jean85** [comment]
Symfony 5 got released (live on stage at SymfonyCon, I've seen it! :smile: )

I'll restart the CI job...

**Comment by TomasVotruba** [comment]
@Jean85 That's not a blocker for this package. If I don't use php-cs-fixer, I could already use these

**Comment by ste93cry** [comment]
The problem is not that it's blocking the installation for someone but that we cannot test the compatibility with Symfony 5 as the test suite cannot be executed to prove that it works, even though as I said I'm sure that it would

**Comment by TomasVotruba** [comment]
Yes, those are 2 different problems.

**Comment by TomasVotruba** [comment]
Ref https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4608

**Comment by rvanlaak** [comment]
What about removing CS Fixer as dependency, and start using https://github.com/jakzal/phpqa or a Github action?

**Comment by Big-Shark** [comment]
@Jean85 PHP-CS-Fixer updated, and now we can restart checkers?

**Comment by ste93cry** [comment]
@rvanlaak can you please force-push? I can restart the Travis CI build but not AppVeyor's one

**Comment by rvanlaak** [comment]
Force push ✔️ checks are still green

**Comment by Jean85** [comment]
It seems that CS-Fixer has the compat on the 2.15.4, but Composer is preferring 2.16.0, which isn't compatible. Also, PHPStan is getting in the way too.

PHPStan will be released as a PHAR from 0.12 so it will auto-resolve, CS-Fixer needs just a tag (the compat is already merged in the 2.16 branch).

**Comment by rvanlaak** [comment]
There is no need to share dependencies with an independent tool like CS-Fixer. What about removing CS-Fixer and running it via the phpqa docker image?

What do you think about merging this PR together with the Symfonyt 5 changes? https://github.com/scribbr/sentry-php/pull/1

**Comment by ste93cry** [comment]
>What about removing CS-Fixer and running it via the phpqa docker image?

There is no reason to use Docker to run in the CI such tools as using the PHARs should be enough. PHPStan 0.12 will be released December 3rd, so let's wait until that date and then let's see what's the status of the dependencies and act accordingly

**Comment by DavidBadura** [comment]
Yeah, tools like php-cs-fixer shouldn't install via composer as dev dependency. You can download it in the CI as phar archive and use that. Otherwise, you will always have the problem that the dependencies do not fit. Either the lib can not be tested with the latest version or the tools can not be updated.

**Comment by ste93cry** [comment]
>Yeah, tools like php-cs-fixer shouldn't install via composer as dev dependency

Sometimes it's convenient to install it that way as you don't have to deal with downloading the PHARs, and sometimes it's necessary as you have to load extensions and it wouldn't be possible by using PHARs: one such example is PHPStan, that's way I'm curious of understanding how `0.12` solves the issue

**Comment by rvanlaak** [comment]
For now it is CS Fixer that is blocking this PR 👍  ... that is why somehow removing it as dependency would be great.

```
$ composer why-not symfony/options-resolver:^5
friendsofphp/php-cs-fixer  v2.16.0     requires  symfony/options-resolver (^3.0 || ^4.0)
```
https://github.com/getsentry/sentry-php/pull/925#pullrequestreview-321716954

If the phar is the way to go, I will make another PR for that.

**Comment by garak** [comment]
You can just require `"friendsofphp/php-cs-fixer": "^2.17@dev"`until a new stable tag will be released.
I tried locally and it works, installing Symfony 5 components (and with green tests)

**Comment by ste93cry** [comment]
>If the phar is the way to go, I will make another PR for that.

No need for another PR, we can use this one :wink: but again, I want to wait PHPStan `0.12` so that we don't have to make one more PR to update how we fetch its PHAR

>You can just require "friendsofphp/php-cs-fixer": "^2.17@dev"until a new stable tag will be released.

It's not a great idea to use a non-stable dependency, isn't it?

**Comment by garak** [comment]
> > You can just require "friendsofphp/php-cs-fixer": "^2.17@dev"until a new stable tag will be released.
> 
> It's not a great idea to use a non-stable dependency, isn't it?

You can do it only on your non-stable release, then everything matches

**Comment by Jean85** [comment]
> You can do it only on your non-stable release, then everything matches

That's not a solution, we want to release a patch and declare compat with SF5. Surely making us indipendent from dev tooling is the best approach, but I agree that a Docker container is a bit overkill here; also, we need to take into account local DX, otherwise noone will fix CS locally and we will get a lot of errors in future PRs.

**Comment by ste93cry** [comment]
PHP-CS-Fixer has been released, @rvanlaak please can you trigger the build one more time?

**Comment by ste93cry** [comment]
LGTM then :+1:

**Comment by rvanlaak** [comment]
Did force-push to rerun CI ✅

**Comment by ste93cry** [comment]
Thank you, even though it was not needed as @Jean85 closed and reopened the PR to forcefully trigger the CI. Everything's fine, LGTM

**Pull request merged**
