### PR TITLE
Feat: Allow passing an eventId as context

### PR DESCRIPTION
**Pull request by jwissels**
We would like to pass an `eventId` as a parameter in the `$record` so that we can communicate the `eventId` to other handlers in the logger.

### CODE REVIEW

**Comment by ste93cry** [comment]
This branch should target the `develop` branch, not `master`

**Comment by ste93cry** [comment]
@cleptric was this closed by mistake? It sounded as a reasonable request 🤔

**Comment by Jean85** [comment]
Wops! We need to protect `develop` then!

**Comment by cleptric** [comment]
@vladanpaunovic Can you do so please?

**Comment by vladanpaunovic** [comment]
Done. `develop` now has same branch protection rules as `master`

**Comment by ste93cry** [comment]
@jwissels do you mind rebasing this PR and removing the extra commits that are coming from `master`?

**Comment by jwissels** [comment]
@ste93cry i'll get on it!

**Comment by jwissels** [comment]
Closing since i cannot update source branch in the PR
see https://github.com/getsentry/sentry-php/pull/1403

**Pull request closed without merging**
