### PR TITLE
Fixed check for exclude

### PR DESCRIPTION
**Pull request by tpdrs**
#953

### CODE REVIEW

**Comment by ste93cry** [comment]
Thank you for the contribution, however this as-is cannot be merged because Unified API docs clearly says that `in_app_include` overrides `in_app_exclude`, so the behavior you're trying to fix is expected and is not a bug, although I think that we all agree that this depending on the needs of each user may or may not be a good thing

>This option can be overridden using in-app-include.
https://docs.sentry.io/error-reporting/configuration/?platform=php#in-app-exclude

**Comment by ste93cry** [comment]
>This PR restores the behavior described in the unified APIs

I would like to clarify this sentence because I feel that it's not: the behavior described in the Unified API is that the `in_app_exclude` option overrides the `in_app_include`, so what has been implemented in `2.3` is the correct behavior and thus there is technically nothing to change. You should not blindly migrate from `project_root` to `in_app_include`: instead you should make each of its entries more specific than the ones in `in_app_exclude` and it should work

**Comment by tpdrs** [comment]
So before I set project_root = /app and excluded /app/vendor, now I have to mention all folders to include (/app/src, /app/bin, /app/tests and don't use app_exclude)

**Comment by tpdrs** [comment]
Let's look to the code

```
    /**
     * Checks whether a certain frame should be marked as "in app" or not.
     *
     * @param string      $file         The file to check
     * @param string|null $functionName The name of the function
     */
    private function isFrameInApp(string $file, ?string $functionName): bool
    {
        if (self::INTERNAL_FRAME_FILENAME === $file) {
            return false;
        }

        if (null !== $functionName && 0 === strpos($functionName, 'Sentry\\')) {
            return false;
        }

        $projectRoot = $this->options->getProjectRoot();
        $excludedAppPaths = $this->options->getInAppExcludedPaths();
        $includedAppPaths = $this->options->getInAppIncludedPaths();
        $absoluteFilePath = @realpath($file) ?: $file;
        $isInApp = false;

        if (null !== $projectRoot) {
            $isInApp = 0 === mb_strpos($absoluteFilePath, $projectRoot);
        }

        foreach ($excludedAppPaths as $excludedAppPath) {
            if (0 === mb_strpos($absoluteFilePath, $excludedAppPath)) {
                $isInApp = false;

                break;
            }
        }

        foreach ($includedAppPaths as $includedAppPath) {
            if (0 === mb_strpos($absoluteFilePath, $includedAppPath)) {
                $isInApp = true;

                break;
            }
        }

        return $isInApp;
    }
```

If you say $projectRoot is deprecated then `$excludedAppPaths` is useless because `$isInApp` by default is `false` and you can remove foreach with check excluded.

**Comment by tpdrs** [comment]
@ste93cry any comments?

**Comment by ste93cry** [comment]
So, there is indeed one bug that should be addressed here: `$isInApp` should be `true` by default. This would make the things working as follow:

- Everything is included by default (regardless of any option)
- `in_app_exclude` sets `$isInApp` to `false` if any entry matches
- `in_app_include` sets `$isInApp` to `true` if any entry matches

With this behavior it's possible to include everything by default, exclude some folders (e.g. `app/vendor`) and still include some paths like `app/vendor/xxx` if needed. Does it makes more sense to you? If so, it would be really cool if you could adjust this PR to fit with the above specs

**Comment by tpdrs** [comment]
@ste93cry I fixed default value for isInApp if in_app_include is not specified.

**Comment by ste93cry** [comment]
As I said above, the default value of `$isInApp` must be true **regardless** of any option, otherwise we will report all files as not-in-app if you didn't configure `$projectRoot` nor `$includedAppPaths` nor `$excludedAppPaths`.

**Comment by tpdrs** [comment]
Fixed

**Comment by tpdrs** [comment]
Yep. This one solves my issues.

**Comment by tpdrs** [comment]
Updated changelog

**Pull request merged**
