### PR TITLE
Fix invalid option name

### PR DESCRIPTION
**Pull request by hhamon**

### CODE REVIEW

**Review by cleptric — APPROVED** [review]
Thank you! 😃

**Comment by cleptric** [comment]
Ohh, could you also update https://github.com/getsentry/sentry-php/blob/master/CHANGELOG.md please?

**Comment by hhamon** [comment]
@cleptric I've updated the other remaining occurrences :)

**Comment by hhamon** [comment]
@cleptric you should also fix it in the release notes off the tagged version

**Comment by cleptric** [comment]
Already updated 🙂

**Pull request merged**
