### PR TITLE
short circuit ignore_exceptions

### PR DESCRIPTION
**Pull request by jspaetzel**
It might be a nice optimization for ignored exceptions to short circuit in captureException? Something like this

### CODE REVIEW

**Comment by jspaetzel** [comment]
Somewhat related to this it might be nice to provide a way to short circuit using a configured callback. I personally would rather implement a callback that hooks into here instead of beforeSend

**Comment by cleptric** [comment]
Your changes look reasonable, thank you!

> Somewhat related to this it might be nice to provide a way to short circuit using a configured callback. I personally would rather implement a callback that hooks into here instead of beforeSend

We could make `ignore_exceptions` accept `callable`, too. I do see the benefit, so why not? 🙂 

`before_send` still has its valid use cases, as it's meant to mutate the event before it is transmitted to Sentry.

**Comment by jspaetzel** [comment]
Agreed! I'll keep this pr small but may open another to have ignore_exceptions accept a callable, I like the sound of that!

**Review by stayallive — APPROVED** [review]
Looks like a good little optimization change to me!

**Review by cleptric — APPROVED** [review]

**Comment by cleptric** [comment]
Released in [v4.6.0](https://github.com/getsentry/sentry-php/releases/tag/4.6.0)

**Pull request merged**
