### PR TITLE
Allow PrettyVersion 2.0

### PR DESCRIPTION
**Pull request by Jean85**
This allows https://github.com/Jean85/pretty-package-versions/releases/tag/2.0.0, which I released with very few BC breaks, so that so we can use both versions without issues. In this PR I'm also able to drop the indirect dependency, so we can move forward toward Composer 2.

I'll probably backport this to the 2.x branch.

### CODE REVIEW

**Comment by Jean85** [comment]
This breaks everything as discussed in https://github.com/getsentry/sentry-symfony/issues/383#issuecomment-760898738 :cry:

**Comment by Jean85** [comment]
This should work with Composer 2.0.9 and PHPStan 0.12.70 as reported in https://github.com/getsentry/sentry-symfony/issues/383#issuecomment-768394725

**Comment by Jean85** [comment]
Ok found the issue: the `ModulesIntegration` is requesting the version of a replaced package (`ocramius/package-version` in this case). I need to understand how to avoid doing that.

**Comment by Jean85** [comment]
@ste93cry @stayallive this is now ready for review! I had to [release a patch](https://github.com/Jean85/pretty-package-versions/releases/tag/2.0.1) to solve this :smile:

**Review by stayallive — APPROVED** [review]
Not knowing enough to know if this is 100% correct and all but I assume you know best in this case 👍

**Review by ste93cry — CHANGES_REQUESTED** [review]
Do we also need a CHANGELOG entry? Not sure about this, it looks like a change of internals that should not impact users :thinking:

**Comment by Jean85** [comment]
I agree that a changelog entry is not needed, this is an internal thing only; the only effect on the outside is that it allows newer version of the dep, and removes an other one.

**Review by ste93cry — APPROVED** [review]

**Pull request merged**
