### PR TITLE
feat: Add guzzle http handler to create spans

### PR DESCRIPTION
**Pull request by HazAT**
This adds a handler for guzzle to be used to create spans for outgoing requests.

CleanShot 2020-09-24 at 14 37 43

Usage: 

```php
use GuzzleHttp\HandlerStack;
use GuzzleHttp\Handler\CurlHandler;
use Sentry\Tracing\GuzzleTracingMiddleware;

$stack = new HandlerStack;
$stack->setHandler(new CurlHandler);
$stack->push(GuzzleTracingMiddleware::trace());

$client = new Client([
    'base_uri' => 'http://httpbin.org',
    'timeout'  => 2.0,
    'handler'  => $stack,
]);

$client->request('GET', '/get');
```

### CODE REVIEW

**Comment by hmazter** [comment]
Fantastic!

**Review by stayallive — APPROVED** [review]
Like it! 👍

**Comment by hmazter** [comment]
I am no expert in Guzzle, but I think it is better to do like this when manually creating the HandlerStack, to get the default middlewares and the auto-decided handler
```diff
- $stack = new HandlerStack;
- $stack->setHandler(new CurlHandler);
+ $stack = HandlerStack::create();
```

**Comment by stayallive** [comment]
@hmazter sounds reasonable, I think the snippet was just meant to (quickly) test it. Ofcourse you can inject the middleware in any handler stack you want, but for the documentation this is probably a better (and cleaner) way to get a stack.

**Pull request merged**
