### PR TITLE
Update Serializer.php

### PR DESCRIPTION
**Pull request by truechudo**
The long text was clipped incorrectly. An error "Malformed UTF-8 characters, possibly incorrectly encoded" occurs in the method  encode in class Raven_Client,  when trying to decode the cropped text.
Sample text:
```
<p><strong class="h2">Борис Васильев. «Не стреляйте в белых лебедей»</strong><br></p>
<p><br></p>
<p> Человек и природа – вот основная тема произведения Бориса Васильева «Не стреляйте в белых лебедей».<br></p>
<p><br></p>
<p> Кто-то, как Егор Полушкин и его сынишка, стараются видеть вокруг красоту и помочь братьям нашим меньшим. А кто-то, как Федор Бурьянов и его сын Вова, смотрят на природу через прицел выгоды.<br></p>
<p><br></p>
<p> Вот из-за таких людей осталось от местного озера только название – «Лебяжье», а когда-то здесь действительно обитали лебеди. Егор Полушкин, поехав на рынок, покупает прекрасных белых лебедей для озера, чтобы возродить его красоту.<br></p>
<p><br></p>
<p> Но если для Егора лебеди - это красота, то для жителей деревни – только гастрономический изыск. <br></p>
<p><br></p>
<p> Беззаветно служа природе, Егор Полушкин отдает ей все, даже свою жизнь. Он не выдал своих обидчиков, наверное, в тайне надеясь на дальнейшее их исправление.<br></p>
<p><br></p>
<attach-media class="center" data-type="images" data-position="1"></attach-media>
<p><br></p>
```

### CODE REVIEW

**Comment by Jean85** [comment]
Thanks for the contribution @truechudo ! Can you add a test to avoid regressing on this bug? Thanks!

**Comment by stayallive** [comment]
Okay fixed the tests but now it's failing on the memory thing again like in #588.

**Comment by Jean85** [comment]
That error should be solvable increasing the memory limit of that regression test... Let's hope we avoid the same failure under 5.3 afterwards!

**Comment by Jean85** [comment]
Damn, same failure...

**Pull request merged**
