### PR TITLE
Replace findUrlFactory with findUriFactory for Psr17FactoryDiscovery

### PR DESCRIPTION
**Pull request by gclove**
https://github.com/php-http/discovery/blob/master/src/Psr17FactoryDiscovery.php#L125-L135

```php
    /**
     * @return UriFactoryInterface
     *
     * @throws Exception\NotFoundException
     *
     * @deprecated This will be removed in 2.0. Consider using the findUriFactory() method.
     */
    public static function findUrlFactory()
    {
        return static::findUriFactory();
    }
```

### CODE REVIEW

**Comment by gclove** [comment]
Sorry, this change is from php-http/discovery `1.11.0` .

https://github.com/php-http/discovery/pull/181

**Comment by ste93cry** [comment]
I think there is no problem in bumping the minimum required version to `1.11`, if it makes it easier to then also support the next major :wink:

**Comment by gclove** [comment]
Thank you, I actually think so too 😂 
May you help me re-run the CI workflows check?

**Review by ste93cry — APPROVED** [review]

**Comment by ste93cry** [comment]
Thank you for the contribution!

**Pull request merged**
