### PR TITLE
[2.0] Do not truncate strings if message limit is set to zero

### PR DESCRIPTION
**Pull request by Jean85**
This is a port of #630 to 2.0

### CODE REVIEW

**Comment by ste93cry** [comment]
Instead of trimming the strings client-side, can't we let the server do it? This way if in the future the limit changes we won't have to do any edit on the client?

Note: I think the new Javascript SDK does not trim too, but I'm not really sure

**Comment by Jean85** [comment]
Well, we could set `0` as the default trim value... WDYT?

**Comment by ste93cry** [comment]
For me it's fine, even though I would like an opinion by @dcramer on the subject

**Comment by dcramer** [comment]
@mitsuhiko 

seems like this would potentially cause problems since messages could be come multiple mb in size

**Comment by Jean85** [comment]
@mitsuhiko @HazAT what do you think of this one? Should we close this or push it forward?

**Comment by mitsuhiko** [comment]
If the event payload gets over the max limit it's entirely discarded by the server. So setting it to 0 never makes sense.

**Comment by ste93cry** [comment]
This means that each SDK needs to be aware of the limit on the server, which seems bad to me. I think it would be better if instead of discarding the entire message it would trim it down itself, but this is out of scope of this PR. At this point I would add a check to ensure that the limit is always greater than 0 and that trimming can't be disabled

**Comment by Jean85** [comment]
Closing this since it seems not desired.

**Pull request closed without merging**
