### PR TITLE
[WIP] Add Windows CI job

### PR DESCRIPTION
**Pull request by Jean85**
This WIP is to try and add a Windows CI job, and avoid issues like #756.

If I will not be able to have a green build, I'll add it to the allowed failures, and fix the SDK in a separate PR.

### CODE REVIEW

**Comment by Jean85** [comment]
Damn, there's an open issue that make the install hang if there's a secret variable: https://travis-ci.community/t/windows-instances-hanging-before-install/250/4

And we have one of those...

**Comment by Jean85** [comment]
Should we pursue (at least temporarely) a different platform for a Windows, like AppVeyor?

@HazAT @ste93cry @stayallive WDYT?

**Comment by ste93cry** [comment]
Imho we should indeed have the Windows build. Travis CI had Windows support in beta since a few months, but I think we will need to wait way more to see stable support for it so probably going with AppVeyor is the best solution at the moment. I don't like to have builds splitted across different CI tools but I don't see any other way

**Comment by Jean85** [comment]
Closing since we're now using AppVeyor from #758

**Pull request closed without merging**
