### PR TITLE
Change specification for autoloading classes

### PR DESCRIPTION
**Pull request by samnela**
Use PSR-4 for autoloading, PSR-0 is deprecated

### CODE REVIEW

**Comment by stayallive** [comment]
Thanks for your contribution, however if you make this change you would also have to namespace all classes and rename them correctly. Currently `Raven_Client` cannot be autoloaded with PSR-4 (because it's not namespaced and following the correct naming convention) as far as I know.

Yes it's currently deprecated but it still works fine everywhere (not seen any composer warnings about it yet). Also there is a lot of work going on in the 2.0 branch that will address this 👍

**Comment by Jean85** [comment]
Yes, 2.0 is already using PSR-4 correctly, see #414 & #440:

https://github.com/getsentry/sentry-php/blob/2.0/composer.json#L46-L53

**Comment by samnela** [comment]
Oh Yes , I hadn't seen  branch 2.0 , really sorry for the noise  .

**Comment by stayallive** [comment]
@samnela don't worry 👍 happy you took the time to make the PR in the first place.

**Pull request closed without merging**
