### PR TITLE
Return EventId only on successful response

### PR DESCRIPTION
**Pull request by tutNichts**
Related to this one: https://github.com/getsentry/sentry-symfony/issues/372

I wasn't able to test this properly yet (will do asap), but at least PHPUnit says "ok".

Feel free to reject it since it feels a bit too simple.

### CODE REVIEW

**Comment by ste93cry** [comment]
No. To be clear, I'm not against the proposed change, I just wanna be sure that the current behavior is not the expected one, then we can proceed with the work

**Comment by tutNichts** [comment]
Anyone wants to add something here?

**Comment by ste93cry** [comment]
From my side, as said before I agree on the usefulness of this change, but on the other side I don't want this SDK to be different than the other ones. @bruno-garcia I will leave the final word about this to you

**Comment by bruno-garcia** [comment]
I'd defer this to @smeubank

**Pull request closed without merging**
