### PR TITLE
Add/Update PHP documentation.

### PR DESCRIPTION
**Pull request by stefangr**
Integrating Raven client in a project when using an IDE is hard because of the lack of documentation.

This commit adds some basic documentation that will ease the implementation when using an IDE.

### CODE REVIEW

**Comment by josegonzalez** [comment]
:+1:

**Comment by nokitakaze** [comment]
Obsolete. Should be closed

**Comment by nokitakaze** [comment]
Obsolete. Should be closed

**Comment by stayallive** [comment]
Thanks for your contribution @stefangr, sorry it took so long.

What @nokitakaze meant by saying it's obsolete is that version 2.0, that is being worked on currently, is going to be properly documented.

**Pull request closed without merging**
